Use Source.queue
apache/pekko-http pull request #537
Opened 2024-04-18 09:29 UTC by laglangyue

2024-04-18 11:19 UTC, pjfanning commented on docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
>  import org.scalatest.matchers.should.Matchers
Keep this with the other pekko imports

2024-04-18 19:15 UTC, He-Pin commented
Cool, thanks, I will check it locally after Friday work

2024-04-18 19:16 UTC, He-Pin commented on docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala
> +    val queue = {
The {} is not needed

2024-04-18 19:16 UTC, He-Pin commented on docs/src/test/scala/docs/http/scaladsl/HttpClientExampleSpec.scala
>  import org.scalatest.matchers.should.Matchers
Yes, sort it with idea or sortimports

2024-04-18 19:59 UTC, samueleresca commented on docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala
> +import org.apache.pekko.stream.QueueOfferResult
`pekko.stream.QueueOfferResult`?

2024-04-19 01:58 UTC, laglangyue commented
thanks for all @pjfanning @He-Pin @samueleresca . I used an idea sort and further manually adjusted it, following the rules of pekko - empty line - and then third-party libraries.

I can't use sortImports in pekko-http, because we not add plugin scalafix

2024-04-19 20:40 UTC, pjfanning approved these changes
lgtm

2024-04-20 06:00 UTC, He-Pin commented on docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala
> +            new RuntimeException("Queue was closed (pool shut down) while running the request. Try again later."))
should be `submitting the request`

2024-04-20 06:02 UTC, He-Pin requested changes
overall lgtm, please update the exception msg

2024-04-20 06:48 UTC, He-Pin commented on docs/src/test/scala/docs/http/scaladsl/Http2ClientApp.scala
> +            new RuntimeException("Queue was closed (pool shut down) while running the request."))
it's not `running`, just submitting or attemptling

2024-04-20 12:50 UTC, He-Pin approved these changes
lgtm, thanks

2024-04-20 15:44 UTC, merged